"use client";

import {
  monogram,
  pickLocalized,
  readableOn,
  safeBrandColor,
} from "@/features/enrollment/localized";
import type { Program } from "@/lib/api/contract";
import { createTranslator, type Translate } from "@/lib/i18n/translator";
import { en } from "@/lib/i18n/messages/en";
import type { Locale } from "@/lib/i18n/config";
import type { PosterLanguage } from "../qr-links";

export type PosterMessages = Record<Locale, Record<string, unknown>>;

/** Translate function for one poster language, from the dictionaries the server sent. */
const translatorFor = (messages: PosterMessages, language: Locale): Translate =>
  createTranslator({ messages: { poster: messages[language] }, fallback: en });

/**
 * A printable join poster: business, what customers earn, the QR code and three steps. A4 proportions with a large
 * code, plain black on white where it matters, and no screen-only decoration, so it prints well in black and
 * white. It shows what the business wrote, as written; the surrounding sentences come in English, Amharic or both.
 */
export function Poster({
  id = "poster-print",
  language,
  qrSvg,
  url,
  merchant,
  program,
  messages,
}: {
  id?: string;
  language: PosterLanguage;
  qrSvg: string;
  url: string;
  merchant: { nameEn: string; nameAm: string | null };
  program: Pick<Program, "nameEn" | "nameAm" | "brandColor" | "stampsRequired" | "reward">;
  messages: PosterMessages;
}) {
  const languages: Locale[] = language === "both" ? ["en", "am"] : [language];
  const color = safeBrandColor(program.brandColor);
  const lead = pickLocalized(languages[0]!, merchant.nameEn, merchant.nameAm);

  return (
    <article
      id={id}
      data-testid="poster"
      data-language={language}
      aria-label={lead.text}
      className="mx-auto flex aspect-[1/1.414] w-full max-w-xl flex-col items-center gap-5 border border-border bg-white p-8 text-center text-black shadow-sm print:max-w-none print:border-0 print:shadow-none"
    >
      <header className="flex w-full flex-col items-center gap-2">
        <span
          aria-hidden="true"
          className="flex h-16 w-16 items-center justify-center rounded-2xl text-3xl font-bold"
          style={{ backgroundColor: color, color: readableOn(color) }}
        >
          {monogram(lead.text)}
        </span>
        {languages.map((lang) => {
          const name = pickLocalized(lang, merchant.nameEn, merchant.nameAm);
          return (
            <p key={lang} className="text-3xl font-bold break-words" lang={name.lang}>
              {name.text}
            </p>
          );
        })}
      </header>

      {languages.map((lang) => {
        const t = translatorFor(messages, lang);
        const reward = program.reward
          ? pickLocalized(lang, program.reward.nameEn, program.reward.nameAm)
          : null;
        return (
          <section key={lang} lang={lang} className="flex flex-col items-center gap-1">
            <h2 className="text-2xl font-bold">{t("poster.heading")}</h2>
            {reward ? (
              <p className="text-lg break-words">
                {t("poster.earn", { count: program.stampsRequired, reward: reward.text })}
              </p>
            ) : null}
          </section>
        );
      })}

      <div
        role="img"
        aria-label={url}
        data-testid="poster-qr"
        className="w-full max-w-72 border-4 border-black bg-white p-2 [&>svg]:h-auto [&>svg]:w-full"
        // Generated by the QR library from the join link; nothing in it is user text.
        dangerouslySetInnerHTML={{ __html: qrSvg }}
      />

      {languages.map((lang) => {
        const t = translatorFor(messages, lang);
        return (
          <section key={lang} lang={lang} className="flex flex-col items-center gap-1">
            <p className="text-xl font-semibold">{t("poster.scan")}</p>
            <ol className="list-inside list-decimal text-base">
              <li>{t("poster.step1")}</li>
              <li>{t("poster.step2")}</li>
              <li>{t("poster.step3")}</li>
            </ol>
            <p className="text-sm">{t("poster.free")}</p>
          </section>
        );
      })}

      <footer className="mt-auto w-full text-xs">
        <p className="font-mono break-all" data-testid="poster-url">
          {url}
        </p>
        <p>{translatorFor(messages, languages[0]!)("poster.footer")}</p>
      </footer>
    </article>
  );
}
