export const FRAUD_INDICATORS = [
  'EXCESSIVE_STAMPS_BY_STAFF',
  'REPEATED_SCANS_FOR_MEMBERSHIP',
  'UNUSUAL_BRANCH_ACTIVITY',
  'HIGH_REVERSAL_RATE',
  'REPEATED_COOLDOWN_REJECTIONS',
  'EXCESSIVE_REDEMPTIONS',
] as const;
export type FraudIndicatorName = (typeof FRAUD_INDICATORS)[number];
